(test
 (name test_hegel)
 (package hegel)
 (modules
  test_hegel
  test_helpers
  test_client
  test_generators_core
  test_generators_primitives
  test_generators_collections
  test_generators_combinators
  test_printing
  test_derive
  test_stateful
  test_single_test_case
  test_antithesis)
 (libraries hegel alcotest core core_unix threads.posix yojson)
 (preprocess
  (pps ppx_js_style -- -allow-unannotated-ignores))
 (foreign_stubs
  (language c)
  (names unsetenv_stubs)))
