import os
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
CORE_REPO = "hegeldev/hegel-core"


def git(*args: str) -> None:
    subprocess.run(["git", *args], check=True, cwd=ROOT)


def get_current_version() -> str:
    text = (ROOT / "lib" / "session.ml").read_text()
    m = re.search(r'^let hegel_server_version = "([^"]+)"', text, re.MULTILINE)
    assert m is not None
    return m.group(1)


def bump(version: str, protocol_version: str) -> None:
    current_version = get_current_version()

    session = ROOT / "lib" / "session.ml"
    text = session.read_text()
    text = re.sub(
        r'^let hegel_server_version = "[^"]+"',
        f'let hegel_server_version = "{version}"',
        text,
        count=1,
        flags=re.MULTILINE,
    )
    session.write_text(text)

    client = ROOT / "lib" / "client.ml"
    text = client.read_text()
    text = re.sub(
        r'^let supported_protocol_lo = "[^"]+"',
        f'let supported_protocol_lo = "{protocol_version}"',
        text,
        count=1,
        flags=re.MULTILINE,
    )
    text = re.sub(
        r'^let supported_protocol_hi = "[^"]+"',
        f'let supported_protocol_hi = "{protocol_version}"',
        text,
        count=1,
        flags=re.MULTILINE,
    )
    client.write_text(text)

    # Note: we intentionally do NOT bump the conformance-harness pin in
    # justfile here. That pin is held at <= 0.4.2 (before
    # CONFORMANCE_SERVER_METRICS_FILE was introduced) so the OCaml binaries
    # don't have to satisfy hegel-core 0.4.13+'s strict per-test-case
    # client/server metrics matching. When that work is done, raise the
    # justfile pin manually.

    flake = ROOT / "nix" / "flake.nix"
    text = flake.read_text()
    text = re.sub(
        r"refs/tags/[^\"]+",
        f"refs/tags/v{version}",
        text,
        count=1,
    )
    flake.write_text(text)

    subprocess.run(
        ["nix", "--extra-experimental-features", "nix-command flakes", "flake", "lock", "./nix"],
        check=True,
        cwd=ROOT,
    )

    current_url = f"https://github.com/{CORE_REPO}/releases/tag/v{current_version}"
    release_url = f"https://github.com/{CORE_REPO}/releases/tag/v{version}"

    release_md = ROOT / "RELEASE.md"
    release_md.write_text(
        f"RELEASE_TYPE: patch\n\n"
        f"This patch bumps our pinned hegel-core from "
        f"[{current_version}]({current_url}) to [{version}]({release_url}).\n"
    )

    app_id = os.environ["HEGEL_RELEASE_APP_ID"]
    git("config", "user.name", "hegel-release[bot]")
    git("config", "user.email", f"{app_id}+hegel-release[bot]@users.noreply.github.com")

    git("checkout", "-b", "ci/bump-hegel-core")
    git(
        "add",
        "lib/session.ml",
        "lib/client.ml",
        "nix/flake.nix",
        "nix/flake.lock",
        "RELEASE.md",
    )
    git("commit", "-m", f"Bump hegel-core to {version}")
    git("push", "--force", "origin", "ci/bump-hegel-core")

    # Only create a PR if one doesn't already exist for this branch.
    # If one exists, the force-push above already updated it.
    result = subprocess.run(
        ["gh", "pr", "list", "--head", "ci/bump-hegel-core", "--state", "open", "--json", "number"],
        capture_output=True,
        text=True,
        cwd=ROOT,
    )
    has_open_pr = result.returncode == 0 and result.stdout.strip() not in ("", "[]")

    title = f"Bump pinned `hegel-core` to `{version}`"
    bump_url = "https://github.com/hegeldev/hegel-ocaml/blob/main/.github/workflows/bump-hegel-core.yml"
    core_url = "https://github.com/hegeldev/hegel-core/blob/main/.github/workflows/ci.yml"
    body = (
        f"This PR bumps our pinned `hegel-core` version to `v{version}`.\n"
        "\n"
        "---\n"
        "\n"
        f"*This PR was automatically generated by [bump-hegel-core.yml]({bump_url})"
        f" after a trigger by [this hegel-core workflow]({core_url}).*"
    )
    if has_open_pr:
        subprocess.run(
            ["gh", "pr", "edit", "ci/bump-hegel-core", "--title", title, "--body", body],
            check=True,
            cwd=ROOT,
        )
    else:
        subprocess.run(
            ["gh", "pr", "create", "--title", title, "--body", body],
            check=True,
            cwd=ROOT,
        )


if __name__ == "__main__":
    bump(os.environ["NEW_VERSION"], os.environ["NEW_PROTOCOL_VERSION"])
