"""Pin a new libhegel release and open/update the bump PR.

Resolves the target hegel-rust version (an explicit argument, else the latest 
release), writes it into `lib/ffi/loader.ml`, regenerates the baked-in checksums 
via the existing `scripts/update-checksums.py`, drops a `RELEASE.md` so merging 
the PR cuts a hegel-ocaml release, and force-pushes a fixed branch (updating an 
already-open PR in place rather than stacking one PR per release).

Requires the GitHub CLI (`gh`) on PATH with `GH_TOKEN` set.
"""

import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
RUST_REPO = "hegeldev/hegel-rust"
BRANCH = "ci/bump-hegel-rust"
LOADER = ROOT / "lib" / "ffi" / "loader.ml"
UPDATE_CHECKSUMS = ROOT / "scripts" / "update-checksums.py"
RELEASE_MD = ROOT / "RELEASE.md"

WORKFLOW_URL = (
    "https://github.com/hegeldev/hegel-ocaml/blob/main/.github/workflows/bump-hegel-rust.yml"
)

VERSION_RE = re.compile(r'^let version = "([^"]+)"', re.MULTILINE)


def git(*args: str) -> None:
    subprocess.run(["git", *args], check=True, cwd=ROOT)


def get_pinned_version() -> str:
    m = VERSION_RE.search(LOADER.read_text(encoding="utf-8"))
    assert m is not None, "could not find `let version` in loader.ml"
    return m.group(1)


def resolve_latest() -> str:
    # `gh release view` with no tag resolves the latest release; strip the
    # leading `v` so it matches the `let version` form (e.g. "0.19.0").
    tag = subprocess.run(
        ["gh", "release", "view", "--repo", RUST_REPO,
         "--json", "tagName", "--jq", ".tagName"],
        check=True, capture_output=True, text=True,
    ).stdout.strip()
    return tag.lstrip("v")


def set_pinned_version(version: str) -> None:
    text = LOADER.read_text(encoding="utf-8")
    new_text, n = VERSION_RE.subn(f'let version = "{version}"', text, count=1)
    assert n == 1, "expected exactly one `let version` line in loader.ml"
    LOADER.write_text(new_text, encoding="utf-8")


def bump(requested: str) -> None:
    current = get_pinned_version()
    target = requested or resolve_latest()

    if target == current:
        print(f"Already pinned to v{current}; nothing to do.")
        return

    # Pin the new version, then regenerate checksums.go-equivalent table.
    # update-checksums.py reads the version back out of loader.ml, so it must
    # be written first.
    set_pinned_version(target)
    subprocess.run([sys.executable, str(UPDATE_CHECKSUMS)], check=True, cwd=ROOT)

    current_url = f"https://github.com/{RUST_REPO}/releases/tag/v{current}"
    new_url = f"https://github.com/{RUST_REPO}/releases/tag/v{target}"

    RELEASE_MD.write_text(
        "RELEASE_TYPE: patch\n\n"
        f"This patch bumps our pinned libhegel ([hegel-rust]({RUST_REPO})) from "
        f"[{current}]({current_url}) to [{target}]({new_url}).\n",
        encoding="utf-8",
    )

    app_id = os.environ["HEGEL_RELEASE_APP_ID"]
    git("config", "user.name", "hegel-release[bot]")
    git("config", "user.email", f"{app_id}+hegel-release[bot]@users.noreply.github.com")

    # A fixed branch that we force-push: an already-open PR is updated in place
    # to the newest version rather than stacking up a new PR per release.
    git("checkout", "-B", BRANCH)
    git("add", str(LOADER), str(RELEASE_MD))
    git("commit", "-m", f"Bump pinned libhegel to {target}")
    git("push", "--force", "origin", BRANCH)

    title = f"Bump pinned `libhegel` to `{target}`"
    body = (
        f"This PR bumps our pinned `libhegel` version to `v{target}`.\n"
        "\n"
        "---\n"
        "\n"
        f"*This PR was automatically generated by [bump-hegel-rust.yml]({WORKFLOW_URL}).*"
    )

    # Only create a PR if one doesn't already exist for this branch; the
    # force-push above already updated an open PR's contents.
    result = subprocess.run(
        ["gh", "pr", "list", "--head", BRANCH, "--state", "open", "--json", "number"],
        capture_output=True,
        text=True,
        cwd=ROOT,
    )
    has_open_pr = result.returncode == 0 and result.stdout.strip() not in ("", "[]")

    if has_open_pr:
        subprocess.run(
            ["gh", "pr", "edit", BRANCH, "--title", title, "--body", body],
            check=True,
            cwd=ROOT,
        )
    else:
        subprocess.run(
            ["gh", "pr", "create", "--title", title, "--body", body],
            check=True,
            cwd=ROOT,
        )


if __name__ == "__main__":
    # An optional argument pins that exact version; with none we take the
    # latest. The repository_dispatch trigger passes client_payload.version.
    bump(sys.argv[1] if len(sys.argv) > 1 else "")
