import os
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
WEBSITE = ROOT / "website"
DOCS_SRC = ROOT / "_build" / "default" / "_doc" / "_html"
DOCS_DEST = WEBSITE / "public" / "ocaml"
BRANCH = "ci/update-ocaml-docs"
# The docs are served at hegel.dev/ocaml. Vercel's `trailingSlash: false` +
# `cleanUrls: true` serve `/ocaml/hegel/Hegel/index.html` at the URL
# `/ocaml/hegel/Hegel` (no trailing slash), so the browser's base directory is
# `/ocaml/hegel/` — one level shallower than the file's real location. odoc's
# relative asset hrefs (`../../odoc.support/odoc.css`, `hegel/index.html`) then
# resolve one directory too high and 404. Injecting an absolute `<base href>`
# equal to each page's own directory makes every relative URL resolve against
# the file's true location regardless of how the slash is stripped.
DOCS_URL_PREFIX = "/ocaml"


def git(*args: str) -> None:
    subprocess.run(["git", *args], check=True, cwd=WEBSITE)


def inject_base_href(root: Path) -> None:
    for html_path in root.rglob("*.html"):
        rel_dir = html_path.parent.relative_to(root).as_posix()
        href = DOCS_URL_PREFIX + "/" + (f"{rel_dir}/" if rel_dir != "." else "")
        tag = f'<base href="{href}">'
        content = html_path.read_text(encoding="utf-8")
        content = content.replace("<head>", f"<head>\n{tag}", 1)
        html_path.write_text(content, encoding="utf-8")


def main() -> None:
    version = os.environ["VERSION"]
    app_id = os.environ["HEGEL_RELEASE_APP_ID"]
    app_slug = os.environ["HEGEL_RELEASE_APP_SLUG"]

    if DOCS_DEST.exists():
        shutil.rmtree(DOCS_DEST)
    # dune emits `_build` files read-only; copy content only (shutil.copyfile,
    # not the default copy2) so the destination is writable for the base-href
    # rewrite below.
    shutil.copytree(DOCS_SRC, DOCS_DEST, copy_function=shutil.copyfile)
    inject_base_href(DOCS_DEST)

    git("config", "user.name", f"{app_slug}[bot]")
    git("config", "user.email", f"{app_id}+{app_slug}[bot]@users.noreply.github.com")

    git("checkout", "-b", BRANCH)
    git("add", "public/ocaml")

    status = subprocess.check_output(
        ["git", "status", "--porcelain"], cwd=WEBSITE, text=True
    )
    if not status.strip():
        print("No doc changes to publish.")
        return

    git("commit", "-m", f"Update hegel-ocaml docs to v{version}")
    git("push", "--force", "origin", BRANCH)

    result = subprocess.run(
        ["gh", "pr", "list", "--head", BRANCH, "--state", "open", "--json", "number"],
        capture_output=True,
        text=True,
        cwd=WEBSITE,
    )
    has_open_pr = result.returncode == 0 and result.stdout.strip() not in ("", "[]")

    title = f"Update `hegel-ocaml` docs to v{version}"
    ci_url = (
        "https://github.com/hegeldev/hegel-ocaml/blob/main/.github/workflows/ci.yml"
    )
    body = (
        f"Updates [hegel-ocaml](https://github.com/hegeldev/hegel-ocaml) docs to "
        f"`v{version}`.\n"
        "\n"
        "---\n"
        "\n"
        f"*This PR was automatically generated by [this workflow]({ci_url}).*"
    )
    cmd = ["gh", "pr", "edit", BRANCH] if has_open_pr else ["gh", "pr", "create"]
    subprocess.run(cmd + ["--title", title, "--body", body], check=True, cwd=WEBSITE)


if __name__ == "__main__":
    main()
