(** Runtime support functions for [@@deriving generator].

    These helpers are used by the code generated by the [ppx_hegel_generator]
    PPX deriver. They are not intended for direct use by end users.

    The PPX generates [Client.test_case -> 'a] functions that call
    {!Hegel.Generators.draw} internally and return typed OCaml values. These
    helpers provide the plumbing for option and list types. *)

(** [generate_option tc gen_fn] generates an [option] value.

    Uses {!Generators.booleans} to decide between [Some] and [None]. When [Some]
    is chosen, calls [gen_fn tc] to produce the inner value. *)
let generate_option tc gen_fn =
  let b = Generators.draw tc (Generators.booleans ()) in
  if b then Some (gen_fn tc) else None

(** [generate_list tc gen_fn] generates a list of values.

    Uses {!Generators.integers} to determine the list length (0-20), then calls
    [gen_fn tc] for each element. *)
let generate_list tc gen_fn =
  let len =
    Generators.draw tc (Generators.integers ~min_value:0 ~max_value:20 ())
  in
  List.init len (fun _ -> gen_fn tc)
