(** Runtime support functions for [@@deriving hegel_generator].

    These helpers are used by the code generated by the [ppx_hegel_generator]
    PPX deriver. They are not intended for direct use by end users.

    The PPX generates [Internal.test_case -> 'a] functions that call
    {!Hegel.Generators.draw} internally and return typed OCaml values. These
    helpers provide the plumbing for option and list types, delegating to the
    same generation machinery as the [Generators.optional] and
    [Generators.lists] combinators. *)

open! Core
open Generators_core

(** [generate_option tc gen_fn] generates an [option] value through the same
    [optional]-spanned machinery as [Generators.optional]: the engine picks
    [None] or [Some] with equal probability, and [gen_fn tc] produces the inner
    value when [Some] is chosen. *)
let generate_option tc gen_fn =
  do_draw (Generators_combinators.optional_core (Leaf { draw = gen_fn })) tc
;;

(** [generate_list tc gen_fn] generates a list of values through the same
    engine-driven collection protocol as [Generators.lists]: the engine decides
    the length (there is no client-side cap) and can delete individual elements
    while shrinking. [gen_fn tc] draws each element. *)
let generate_list tc gen_fn =
  do_draw
    (CompositeList { elements = Leaf { draw = gen_fn }; min_size = 0; max_size = None })
    tc
;;
