(** Runtime support functions for [@@deriving hegel_generator].

    These helpers are used by the code generated by the [ppx_hegel_generator]
    PPX deriver. They are not intended for direct use by end users. *)

(** [generate_option tc gen_fn] generates an [option] value.

    Uses {!Generators.booleans} to decide between [Some] and [None]. When [Some]
    is chosen, calls [gen_fn tc] to produce the inner value. *)
val generate_option : Internal.test_case -> (Internal.test_case -> 'a) -> 'a option

(** [generate_list tc gen_fn] generates a list of values.

    Uses {!Generators.integers} to determine the list length (0-20), then calls
    [gen_fn tc] for each element. *)
val generate_list : Internal.test_case -> (Internal.test_case -> 'a) -> 'a list
