(** Runtime support functions for [@@deriving hegel_generator].

    These helpers are used by the code generated by the [ppx_hegel_generator]
    PPX deriver. They are not intended for direct use by end users. *)

(** [generate_option tc gen_fn] generates an [option] value through the same
    [optional]-spanned machinery as [Generators.optional]: the engine picks
    [None] or [Some] with equal probability, calling [gen_fn tc] for the inner
    value when [Some] is chosen. *)
val generate_option : Internal.test_case -> (Internal.test_case -> 'a) -> 'a option

(** [generate_list tc gen_fn] generates a list of values through the same
    engine-driven collection protocol as [Generators.lists]: the engine decides
    the length (no client-side cap) and can delete individual elements while
    shrinking. [gen_fn tc] draws each element. *)
val generate_list : Internal.test_case -> (Internal.test_case -> 'a) -> 'a list
