(** Runtime support functions for [@@deriving generator].

    These helpers are used by the code generated by the [ppx_hegel_generator]
    PPX deriver. They are not intended for direct use by end users. *)

(** [generate_option gen_fn] generates an [option] value.

    Uses {!Generators.booleans} to decide between [Some] and [None]. When [Some]
    is chosen, calls [gen_fn ()] to produce the inner value. Must be called from
    within a Hegel test body. *)
val generate_option : (unit -> 'a) -> 'a option

(** [generate_list gen_fn] generates a list of values.

    Uses {!Generators.integers} to determine the list length (0-20), then calls
    [gen_fn ()] for each element. Must be called from within a Hegel test body. *)
val generate_list : (unit -> 'a) -> 'a list
