(library
 (name hegel)
 (public_name hegel)
 (libraries core core_unix hegel_ffi ipaddr threads.posix yojson)
 (private_modules
  generators_core
  generators_primitives
  generators_collections
  generators_combinators
  pretty)
 (preprocess
  (pps ppx_js_style))
 (instrumentation
  (backend bisect_ppx)))
